### ISSUE TITLE
Regression of GitHub website following .NET 8 migration

### ISSUE THREAD

**Issue by TheBoxyBear** [TheBoxyBear/ChartTools#62]
The automated deployment process to GitHub Pages using NUnit/docfx-action required the action be updated to version 3.0.0 for .NET 8 support. Doing so also updated DocFx to the latest version which introduces an infinite recursion bug when building. Building locally using the Docs project and its docfx.console package is not affected as the package uses an outdated version of DocFx.

**Comment by TheBoxyBear** [comment]
Issue has been reported to DocFx maintainers https://github.com/dotnet/docfx/issues/9236#issuecomment-1877725210

**Comment by filzrev** [comment]
It seems docfx custom template is used for documentation.

As described by latest version of release note.
This problem can be fixed by renaming `toc.html.tmpl` file name to `toc.html.primary.tmpl`.
